#!/bin/sh

if [ -z "${NO_ANNOUNCE}" ]; then
	log "Checking for announcement from blek.codes..."

	# get announcement
	DATA=$(curl -s https://blek.codes/announce.json -m 1)
	if [[ $(echo "$DATA" | jq -r '.broadcast') == "true" ]]; then
		log "Message from \033[36m\033[1mblek.codes\033[0m: $(echo $DATA | jq -r '.data.inline')";
	else
		log "No message from blek.codes";
	fi
fi
