#!/bin/sh

tail -n+1 -F /var/log/nginx/access.log | xargs -I {} echo -e "[$(date '+%Y-%m-%d %H:%M:%S') | \033[37m\033[1mINFO\033[0m  ] [\033[36m\033[1mN\033[0m] {}" & \
tail -n+1 -F /var/log/nginx/error.log | xargs -I {} echo -e "[$(date '+%Y-%m-%d %H:%M:%S') | \033[31m\033[1mERROR\033[0m ] [\033[36m\033[1mN\033[0m] {}"

while true; do
    sleep 10000
done
